version: '3.8'

services:
  devicesapi:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=192.168.0.100;Port=5432;Database=devicesdb;Username=postgres;Password=postgres
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
